"""Observability: Prometheus metrics, SLIs/SLOs and alert evaluation
(Phase 12, CLAUDE.md §40, §43).

Metrics (all exposed on /metrics in Prometheus text format):

- http_requests_total                 counter  {method, path, status}
- http_request_duration_seconds       histogram{method, path}
- billing_records_processed_total     counter  {result}
- billing_data_freshness_seconds      gauge    (age of the newest data day)
- recommendations_generated_total     counter  {rule?} -> plain count
- forecast_runs_total                 counter  {result}
- bigquery_query_duration_seconds     histogram

Plus `recommendation_runs_total {result}` so the recommendation-success SLI
can distinguish successful runs from failures.

SLIs/SLOs (CLAUDE.md §43):
- API availability           >= 99.5%  (non-5xx / all requests)
- Billing data freshness     <  24h    (age of newest data day)
- Recommendation success     >= 99%    (successful runs / runs)

Alerts are evaluated in-process (`/api/alerts`) and mirrored as Prometheus
alert rules in monitoring/prometheus-rules.yml for real deployments.
"""

from __future__ import annotations

from typing import Any

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)

SLO_AVAILABILITY = 0.995
SLO_FRESHNESS_SECONDS = 24 * 3600.0
SLO_RECOMMENDATION_SUCCESS = 0.99

http_requests_total = Counter(
    "http_requests_total",
    "Total HTTP requests handled.",
    ["method", "path", "status"],
)
http_request_duration_seconds = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds.",
    ["method", "path"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)
billing_records_processed_total = Counter(
    "billing_records_processed_total",
    "Billing cost records processed by the ingestion loader.",
    ["result"],
)
billing_data_freshness_seconds = Gauge(
    "billing_data_freshness_seconds",
    "Age of the newest billing data day in seconds.",
)
recommendations_generated_total = Counter(
    "recommendations_generated_total",
    "Recommendations generated by the rule engine.",
)
recommendation_runs_total = Counter(
    "recommendation_runs_total",
    "Recommendation engine runs, by result.",
    ["result"],
)
forecast_runs_total = Counter(
    "forecast_runs_total",
    "Forecast computations, by result.",
    ["result"],
)
bigquery_query_duration_seconds = Histogram(
    "bigquery_query_duration_seconds",
    "BigQuery query duration in seconds.",
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0),
)


def render_metrics() -> tuple[bytes, str]:
    return generate_latest(), CONTENT_TYPE_LATEST


def observe_request(method: str, path_label: str, status: int, duration_seconds: float) -> None:
    """Instrument one handled request (called from the middleware)."""
    status_label = str(status)
    http_requests_total.labels(method=method, path=path_label, status=status_label).inc()
    http_request_duration_seconds.labels(method=method, path=path_label).observe(duration_seconds)


def set_freshness_gauge(age_seconds: float | None) -> None:
    """Publish the newest-data age. None (no data) resets the gauge to 0 —
    the UNKNOWN state is carried by the freshness endpoint, not the gauge."""
    if age_seconds is not None:
        billing_data_freshness_seconds.set(age_seconds)


# ---------------------------------------------------------------------------
# SLIs, SLOs and alerts
# ---------------------------------------------------------------------------


def _requests_by_status() -> dict[str, float]:
    by_status: dict[str, float] = {}
    for metric in http_requests_total.collect():
        for sample in metric.samples:
            if sample.name.endswith("_total"):
                by_status[sample.labels.get("status", "?")] = (
                    by_status.get(sample.labels.get("status", "?"), 0.0) + sample.value
                )
    return by_status


def availability_sli() -> dict[str, Any]:
    """API availability: non-5xx requests / all requests (process lifetime)."""
    by_status = _requests_by_status()
    total = sum(by_status.values())
    if total == 0:
        return {"sli": None, "slo": SLO_AVAILABILITY, "met": None, "requests": 0}
    server_errors = sum(value for status, value in by_status.items() if status.startswith("5"))
    availability = 1 - server_errors / total
    return {
        "sli": round(availability, 6),
        "slo": SLO_AVAILABILITY,
        "met": availability >= SLO_AVAILABILITY,
        "requests": int(total),
        "server_errors": int(server_errors),
    }


def freshness_sli(freshness: dict[str, Any]) -> dict[str, Any]:
    """Billing data freshness against the 24h SLO."""
    age = freshness.get("data_age_hours")
    if age is None or freshness.get("status") == "UNKNOWN":
        return {"sli": None, "slo": SLO_FRESHNESS_SECONDS, "met": None, "status": "UNKNOWN"}
    age_seconds = age * 3600.0
    return {
        "sli": age_seconds,
        "slo": SLO_FRESHNESS_SECONDS,
        "met": age_seconds < SLO_FRESHNESS_SECONDS,
        "status": freshness.get("status"),
    }


def recommendation_success_sli() -> dict[str, Any]:
    """Recommendation pipeline success: successful runs / all runs."""
    runs: dict[str, float] = {}
    for metric in recommendation_runs_total.collect():
        for sample in metric.samples:
            if sample.name.endswith("_total"):
                result = sample.labels.get("result", "?")
                runs[result] = runs.get(result, 0.0) + sample.value
    total = sum(runs.values())
    if total == 0:
        return {"sli": None, "slo": SLO_RECOMMENDATION_SUCCESS, "met": None, "runs": 0}
    success = runs.get("success", 0.0) / total
    return {
        "sli": round(success, 6),
        "slo": SLO_RECOMMENDATION_SUCCESS,
        "met": success >= SLO_RECOMMENDATION_SUCCESS,
        "runs": int(total),
    }


def compute_reliability(session: Any, freshness: dict[str, Any]) -> dict[str, Any]:
    """All SLIs vs their SLO targets, for /api/reliability."""
    return {
        "slos": {
            "api_availability": {"target": SLO_AVAILABILITY, "unit": "ratio"},
            "billing_data_freshness": {
                "target": SLO_FRESHNESS_SECONDS,
                "unit": "seconds",
                "human": "billing data age < 24h",
            },
            "recommendation_success": {"target": SLO_RECOMMENDATION_SUCCESS, "unit": "ratio"},
        },
        "slis": {
            "api_availability": availability_sli(),
            "billing_data_freshness": freshness_sli(freshness),
            "recommendation_success": recommendation_success_sli(),
        },
    }


def evaluate_alerts(freshness: dict[str, Any]) -> list[dict[str, Any]]:
    """Basic in-process alert evaluation (mirrored in
    monitoring/prometheus-rules.yml for real Prometheus deployments)."""
    alerts: list[dict[str, Any]] = []

    # INC-001 Billing stale
    if freshness.get("status") == "UNKNOWN":
        alerts.append(
            {
                "name": "BillingDataMissing",
                "severity": "critical",
                "state": "firing",
                "description": "No billing data at all — freshness is UNKNOWN.",
                "runbook": "docs/runbook.md#inc-001-billing-stale",
            }
        )
    else:
        age_hours = freshness.get("data_age_hours")
        firing = age_hours is not None and age_hours > 24
        alerts.append(
            {
                "name": "BillingDataStale",
                "severity": "warning",
                "state": "firing" if firing else "ok",
                "description": (
                    f"Billing data is {age_hours:.0f}h old (SLO < 24h)."
                    if age_hours is not None
                    else "Billing data age unknown."
                ),
                "runbook": "docs/runbook.md#inc-001-billing-stale",
            }
        )

    # INC-003 API outage (availability SLO)
    availability = availability_sli()
    alerts.append(
        {
            "name": "APIAvailabilityLow",
            "severity": "critical",
            "state": "firing" if availability["met"] is False else "ok",
            "description": (
                f"API availability {availability['sli']} below the 99.5% SLO."
                if availability["sli"] is not None
                else "No requests observed yet."
            ),
            "runbook": "docs/runbook.md#inc-003-api-outage",
        }
    )

    # INC-004 Recommendation failure
    rec = recommendation_success_sli()
    firing = rec["met"] is False and rec.get("runs", 0) >= 5
    alerts.append(
        {
            "name": "RecommendationPipelineFailing",
            "severity": "warning",
            "state": "firing" if firing else "ok",
            "description": (
                f"Recommendation success {rec['sli']} below the 99% SLO over {rec['runs']} runs."
                if rec["sli"] is not None
                else "No recommendation runs yet."
            ),
            "runbook": "docs/runbook.md#inc-004-recommendation-failure",
        }
    )

    # INC-002 BigQuery failure (observed via the query duration metric's count
    # and the billing freshness together); the incident doc covers the flow.
    return alerts
